// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Persistence.Migrations.GalleryMySqlDb
{
    [DbContext(typeof(GalleryMySqlDbContext))]
    [Migration("20210420091403_Codes_Translations_Init")]
    partial class Codes_Translations_Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Domain.Entities.Code", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("Domain.Entities.CodeLanguage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CodeId")
                        .HasColumnType("bigint");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Translation")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("LanguageId");

                    b.ToTable("CodesLanguages");
                });

            modelBuilder.Entity("Domain.Entities.Language", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Domain.Entities.Code", b =>
                {
                    b.HasOne("Domain.Entities.Code", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_Codes_Codes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Entities.CodeLanguage", b =>
                {
                    b.HasOne("Domain.Entities.Code", "Code")
                        .WithMany("CodesLanguages")
                        .HasForeignKey("CodeId")
                        .HasConstraintName("FK_CodesLanguages_Codes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Language", "Language")
                        .WithMany("CodesLanguages")
                        .HasForeignKey("LanguageId")
                        .HasConstraintName("FK_CodesLanguages_Languages")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Code");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Domain.Entities.Code", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("CodesLanguages");
                });

            modelBuilder.Entity("Domain.Entities.Language", b =>
                {
                    b.Navigation("CodesLanguages");
                });
#pragma warning restore 612, 618
        }
    }
}
